/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhp' at '16-3-23 下午3:59' with Gradle 2.11
 *
 * @author zhp, @date 16-3-23 下午3:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
